apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-ingress
  namespace: argocd
spec:
  project: default
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 5.45.0
    helm:
      releaseName: argocd
      valueFiles:
      - values/argocd.yaml   
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true    