apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-metallb
  namespace: argocd
spec:
  project: default
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.10
    helm:
      releaseName: metallb
      valueFiles:
        - values/metallb.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
